### ISSUE TITLE
Question about update anomalies if tenant_name is in multiple tables

### ISSUE THREAD

**Issue by joeferng** [bytefish/SpringBootMultitenancyUsingRowLevelSecurity#1]
Hi, great article about using RLS to support multitenancy. I have a question about what to do if multiple tables have the tenant_name. Expanding on the example in the article, what if there was a customer_address table (with a foreign key customer_id to the customer table) to store the customer addresses, and what if the customer_address table also had a tenant_name column? In this case, could there be a data anomaly where the customer address is associated to one tenancy, but the customer itself could be associated to a different tenancy? Thank you again for your article.

**Comment by bytefish** [comment]
I have added a more complete example, that shows how to work with multiple tables when inserting data. I have also extended the SQL Script to set a RLS Policy on all tables, so you only see data visible for the tenant.... also including join tables. I think this is a good start, if you want to experiment with it.
