### ISSUE TITLE
More than 10 DB?

### ISSUE THREAD

**Issue by somera** [bytefish/SpringBootMultitenancyUsingRowLevelSecurity#2]
What can the configuration look like if you have more than 10 databases? For example you have 1.000.000 users and 10 databases. And every database should store 100.000 users. And in the front a lookup db with user-uuid -> db-name.

**Comment by bytefish** [comment]
There are no multiple databases for this example. All Tenants share the same database, while the data is still being isolated using Postgres Row Level Security implementation.
